NMP-Database/NMP-Database/DBO/StoredProcedures/Farms/spFarms_GetUserFarms.sql, NMP-Database/NMP-Database/DBO/Tables/Crops.sql, NMP-Database/NMP-Database/DBO/Tables/Fields.sql, NMP-Database/NMP-Database/DBO/Tables/SoilAnalyses.sql, NMP-Database/NMP-Database/NMP-Database.sqlproj
Crop and Soil Analysis table added
=> Crop and Soil Analysis table created

NMP-Database/NMP-Database/DBO/Tables/Countries.sql
need to change HighReadilyAvailableNitrogen column in postscript
=> Feature update manure type table

NMP-Database/NMP-Database/DBO/Tables/Farms.sql
=> Fetaure change rainfall datatype in farm table

NMP-Database/NMP-Database/DBO/Tables/FertiliserManures.sql, NMP-Database/NMP-Database/DBO/Tables/InOrganicManureDurations.sql
little modifications
1. id to ID
2. foreign key naming convention correction
=> Feature id column change in in organic manure durations

NMP-Database/NMP-Database/DBO/Tables/InOrganicManureDurations.sql
column name change in InOrganicManureDurations
Changes in Post script according to new columns
=> column name change in InOrganicManureDurations

NMP-Database/NMP-Database/DBO/Tables/CropTypeLinkings.sql
NMax limit column in cropTypeLinking table
=> NMax limit column in cropTypeLinking table

NMP-Database/NMP-Database/DBO/Tables/Crops.sql
CropOrder column added in crop table
=> CropOrder column added in crop table

NMP-Database/NMP-Database/DBO/Tables/CropTypeLinkings.sql, NMP-Database/NMP-Database/DBO/Tables/SNSCategories.sql, NMP-Database/NMP-Database/NMP-Database.sqlproj
new table and post script added
=> Feature new table sns category

NMP-Database/NMP-Database/DBO/Tables/PKBalances.sql, NMP-Database/NMP-Database/NMP-Database.refactorlog, NMP-Database/NMP-Database/NMP-Database.sqlproj
=> addded PKBalance Table

NMP-Database/NMP-Database/DBO/Tables/PKBalances.sql
added Created By, Modified By column.
=> added CreatedBy, ModifiedBy column .

NMP-Database/NMP-Database/Script.PreDeployment.sql
=> Feature modification in country table

NMP-Database/NMP-Database/DBO/Tables/Farms.sql, NMP-Database/NMP-Database/DBO/Tables/SnsAnalyses.sql, NMP-Database/NMP-Database/Script.PostDeployment.sql
Added CurrentCropTypeID column 
little modification in Post script
=> Feature added current crop type id into sns analyses

NMP-Database/NMP-Database/DBO/StoredProcedures/Farms/spFarms_DeleteFarm.sql
Changes in delete farm stored procedure
=> Added Excess Rainfall in delete farm stored procedure

NMP-Database/NMP-Database/DBO/Tables/Crops.sql
=> Feature nmpt652

NMP-Database/NMP-Database/DBO/StoredProcedures/Crops/spCrops_GetPlansByHarvestYear.sql
added cropGroupName column into sp
=> added cropGroupName column into sp

NMP-Database/NMP-Database/DBO/StoredProcedures/Crops/spCrops_GetPlansByHarvestYear.sql, NMP-Database/NMP-Database/DBO/StoredProcedures/Recommendations/spRecommendations_GetRecommendations.sql
some modification for NMPT-1044
=> some modification for NMPT-1044

NMP-Database/NMP-Database/DBO/Tables/ExcessWinterRainfallOptions.sql, NMP-Database/NMP-Database/NMP-Database.sqlproj, NMP-Database/NMP-Database/Script.PostDeployment.sql
added ExcessWinterRainfallOptions table
=> added ExcessWinterRainfallOptions table

NMP-Database/NMP-Database/DBO/StoredProcedures/Crops/spCrops_GetPlansByHarvestYear.sql
changes for update crop group name
=> column added

NMP-Database/NMP-Database/DBO/StoredProcedures/FertiliserManures/spFertiliserManures_GetByFarmIdAndYear.sql, NMP-Database/NMP-Database/NMP-Database.sqlproj
=> changs for NMPT1236

NMP-Database/NMP-Database/DBO/StoredProcedures/FertiliserManures/spFertiliserManures_GetByFarmIdAndYear.sql
=> little changes

NMP-Database/NMP-Database/DBO/StoredProcedures/OrganicManures/spOrganicManures_GetByFarmIdAndYear.sql, NMP-Database/NMP-Database/NMP-Database.sqlproj
added one store procedure for organic manure
=> added one store procedure for organic manure

NMP-Database/NMP-Database/DBO/StoredProcedures/Crops/spCrops_GetPlansByHarvestYear.sql
=> little change for grass

NMP-Database/NMP-Database/DBO/StoredProcedures/Crops/spCrops_GetPlansByHarvestYear.sql
=> added two columns

NMP-Database/NMP-Database/Script.PostDeployment.sql, NMP-Database/NMP-Database/Script.PreDeployment.sql
UPDATE NMaxLimitEngland COLUMN data
=> UPDATE NMaxLimitEngland COLUMN

NMP-Database/NMP-Database/DBO/Tables/StoreCapacities.sql
changes in store capacity table
=> changes in store capacity table

NMP-Database/NMP-Database/Script.PostDeployment.sql
"to" has been removed from Id 1 in LivestockTypes
=> Feature little change in livestock name

NMP-Database/NMP-Database/Script.PostDeployment.sql
liitle change in script for livestock
=> liitle change

NMP-Database/NMP-Database/DBO/Tables/WarningCodes.sql, NMP-Database/NMP-Database/DBO/Tables/WarningLevels.sql, NMP-Database/NMP-Database/DBO/Tables/WarningMessages.sql, NMP-Database/NMP-Database/NMP-Database.sqlproj, NMP-Database/NMP-Database/Script.PostDeployment.sql
Added Warning message,WarningCode,WarningLevel table and insert script
=> Added Warning message,WarningCode,WarningLevel table and insert script

NMP-Database/NMP-Database/DBO/Tables/OrganicManures.sql, NMP-Database/NMP-Database/Script.PreDeployment.sql
change autumn uptake column data type
=> change autumn uptake column data type
